# only interactive
[[ -o interactive ]] || return

source ~/dotfiles/shell/aliases.sh
source ~/dotfiles/shell/prompt.sh

autoload -U colors && colors

PINK="%F{218}"
BLUE="%F{110}"
GRAY="%F{245}"
PURPLE="%F{177}"

RESET="%f"

ECHO_PINK="\e[38;5;218m"
ECHO_RESET="\e[0m"

print
print "  ✧( •̀ ω •́ )      ( •̀ ω •́ )✧"
print "  ───────────────────────────"
print "     ${ECHO_PINK}welcome back, soso 🌸${ECHO_RESET}"
print

set_prompt() {
  PROMPT="${PINK}💗 ${BLUE}%n@%m ${GRAY}%~ ${PINK}$(git_branch)${RESET}
${PINK}❯${PURPLE}❯${BLUE}❯${RESET} "
}

precmd() {
  set_prompt
}
