# only interactive
[[ $- != *i* ]] && return

# Auto-switch to Zsh if available and interactive
if [[ -t 0 && -x $(command -v zsh) && $(ps -p $$ -o comm=) != "zsh" ]]; then
    exec zsh
fi

source ~/dotfiles/shell/aliases.sh
source ~/dotfiles/shell/prompt.sh


# colors (bash style)
RESET="\[\e[0m\]"
PINK="\[\e[38;5;218m\]"
BLUE="\[\e[38;5;110m\]"
GRAY="\[\e[38;5;245m\]"
PURPLE="\[\e[38;5;177m\]"

ECHO_PINK="\e[38;5;218m"
ECHO_RESET="\e[0m"

echo
echo -e "  ✧( •̀ ω •́ )      ( •̀ ω •́ )✧"
echo -e "  ───────────────────────────"
echo -e "     ${ECHO_PINK}welcome back, soso 🌸${ECHO_RESET}"
echo

# history
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoredups:erasedups
shopt -s histappend

set -o noclobber
set -o notify

git_branch() {
  git branch 2>/dev/null | sed -n '/\* /s///p'
}

set_prompt() {
  PS1="${PINK}💗 ${BLUE}\u@\h ${GRAY}\w ${PINK}$(git_branch)${RESET}\n${PINK}❯${PURPLE}❯${BLUE}❯${RESET} "
}


PROMPT_COMMAND=set_prompt
